export const SET_SELECTED_DAY = 'SET_SELECTED_DAY';
export const REFRESH_DAY_LIST = 'REFRESH_DAY_LIST';
export const SET_SELECTED_NEIGHBORHOOD = 'SET_SELECTED_NEIGHBORHOOD';
export const REFRESH_NEIGHBORHOOD_LIST = 'REFRESH_NEIGHBORHOOD_LIST';
export const SET_SELECTED_TIME = 'SET_SELECTED_TIME';
export const REFRESH_TIME_LIST = 'REFRESH_TIME_LIST';
export const REFRESH_FOOD_LIST = 'REFRESH_FOOD_LIST';